src/Web/CinemaWorld.Web/Areas/Administration/Controllers/NewsController.cs
namespace CinemaWorld.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using CinemaWorld.Data.Models;
    using CinemaWorld.Models.InputModels.AdministratorInputModels.News;
    using CinemaWorld.Models.ViewModels.News;
    using CinemaWorld.Services.Data.Contracts;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class NewsController : AdministrationController
    {
        private readonly INewsService newsService;
        private readonly UserManager<CinemaWorldUser> userManager;

        public NewsController(INewsService newsService, UserManager<CinemaWorldUser> userManager)
        {
            this.newsService = newsService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewsCreateInputModel newsCreateInputModel)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.ModelState.IsValid)
            {
                return this.View(newsCreateInputModel);
            }

            await this.newsService.CreateAsync(newsCreateInputModel, user.Id);
            return this.RedirectToAction("GetAll", "News", new { area = "Administration" });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var newsToEdit = await this.newsService
                .GetViewModelByIdAsync<NewsEditViewModel>(id);

            return this.View(newsToEdit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(NewsEditViewModel newsEditViewModel)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.ModelState.IsValid)
            {
                return this.View(newsEditViewModel);
            }

            await this.newsService.EditAsync(newsEditViewModel, user.Id);
            return this.RedirectToAction("GetAll", "News", new { area = "Administration" });
        }

        public async Task<IActionResult> Remove(int id)
        {
            var newsToDelete = await this.newsService.GetViewModelByIdAsync<NewsDeleteViewModel>(id);
            return this.View(newsToDelete);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(AllNewsListingViewModel newsDetailsViewModel)
        {
            await this.newsService.DeleteByIdAsync(newsDetailsViewModel.Id);
            return this.RedirectToAction("GetAll", "News", new { area = "Administration" });
        }

        public async Task<IActionResult> GetAll()
        {
            var news = await this.newsService.GetAllNewsAsync<AllNewsListingViewModel>();
            return this.View(news);
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/MoviesController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels;
    using CinemaWorld.Models.ViewModels.Movies;
    using CinemaWorld.Services.Data.Contracts;
    using CinemaWorld.Web.Helpers;

    using Microsoft.AspNetCore.Mvc;

    public class MoviesController : Controller
    {
        private const int PageSize = 10;

        private readonly IMoviesService moviesService;

        public MoviesController(IMoviesService moviesService)
        {
            this.moviesService = moviesService;
        }

        public async Task<IActionResult> All(string searchString, string currentFilter, string selectedLetter, int? pageNumber)
        {
            this.ViewData["Current"] = nameof(this.All);

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            this.ViewData["CurrentSearchFilter"] = searchString;
            var movies = this.moviesService
                .GetAllMoviesByFilterAsQueryeable<MovieDetailsViewModel>(selectedLetter);

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.Name.ToLower().Contains(searchString.ToLower()));
            }

            var moviesPaginated = await PaginatedList<MovieDetailsViewModel>.CreateAsync(movies, pageNumber ?? 1, PageSize);

            var alphabeticalPagingViewModel = new AlphabeticalPagingViewModel
            {
                SelectedLetter = selectedLetter,
            };

            var viewModel = new MoviesListingViewModel
            {
                Movies = moviesPaginated,
                AlphabeticalPagingViewModel = alphabeticalPagingViewModel,
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await this.moviesService.GetViewModelByIdAsync<MovieDetailsViewModel>(id);
            var topRatingMovies = await this.moviesService.GetAllMoviesAsync<TopRatingMovieDetailsViewModel>();

            string videoId = ExtractVideoHelper.ExtractVideoId(movie.TrailerPath);
            movie.TrailerPath = videoId;

            var viewModel = new DetailsListingViewModel
            {
                MovieDetailsViewModel = movie,
                AllMovies = topRatingMovies,
            };

            return this.View(viewModel);
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/NewsCommentsController.cs
namespace CinemaWorld.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using CinemaWorld.Data.Models;
    using CinemaWorld.Models.InputModels.NewsComments;
    using CinemaWorld.Services.Data.Contracts;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class NewsCommentsController : Controller
    {
        private readonly INewsCommentsService newsCommentsService;
        private readonly UserManager<CinemaWorldUser> userManager;

        public NewsCommentsController(
            INewsCommentsService commentsService,
            UserManager<CinemaWorldUser> userManager)
        {
            this.newsCommentsService = commentsService;
            this.userManager = userManager;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateNewsCommentInputModel input)
        {
            var parentId = input.ParentId == 0 ? (int?)null : input.ParentId;

            if (parentId.HasValue)
            {
                if (!await this.newsCommentsService.IsInNewsId(parentId.Value, input.NewsId))
                {
                    return this.BadRequest();
                }
            }

            var userId = this.userManager.GetUserId(this.User);

            try
            {
                await this.newsCommentsService.CreateAsync(input.NewsId, userId, input.Content, parentId);
            }
            catch (ArgumentException aex)
            {
                return this.BadRequest(aex.Message);
            }

            return this.RedirectToAction("Details", "News", new { id = input.NewsId });
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/NewsController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels;
    using CinemaWorld.Models.ViewModels.Movies;
    using CinemaWorld.Models.ViewModels.News;
    using CinemaWorld.Services.Data.Contracts;

    using Microsoft.AspNetCore.Mvc;

    public class NewsController : Controller
    {
        private const int NewsCount = 6;
        private const int LatestMoviesCount = 6;
        private const int TopMoviesCount = 10;

        private readonly INewsService newsService;
        private readonly IMoviesService moviesService;

        public NewsController(INewsService newsService, IMoviesService moviesService)
        {
            this.newsService = newsService;
            this.moviesService = moviesService;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            var news = await Task.Run(
                () => this.newsService.GetAllNewsAsQueryeable<AllNewsListingViewModel>());

            var newsPaginated = await PaginatedList<AllNewsListingViewModel>
                .CreateAsync(news, pageNumber ?? 1, NewsCount);
            var updatedNews = await this.newsService
                .GetUpdatedNewsAsync<UpdatedNewsDetailsViewModel>();
            var topNews = await this.newsService
                .GetTopNewsAsync<TopNewsViewModel>(TopMoviesCount);

            var viewModel = new NewsIndexViewModel
            {
                News = newsPaginated,
                UpdatedNews = updatedNews,
                TopNews = topNews,
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var news = await this.newsService
                .SetViewsCounter(id);
            var latestMovies = await this.moviesService
                .GetRecentlyAddedMoviesAsync<RecentlyAddedMovieDetailsViewModel>(LatestMoviesCount);
            var topNews = await this.newsService
                .GetTopNewsAsync<TopNewsViewModel>(TopMoviesCount);

            var viewModel = new NewsSingleDetailsViewModel
            {
                News = news,
                LatestMovies = latestMovies,
                TopNews = topNews,
            };

            return this.View(viewModel);
        }
    }
}

src/Web/CinemaWorld.Web/Views/News/Details.cshtml
@using CinemaWorld.Models.ViewModels.News
@model NewsSingleDetailsViewModel
@{
    ViewData["Title"] = "Single";

    void DisplayComments(int? parentId)
    {
        var comments = this.Model.News.NewsComments.Where(x => x.ParentId == parentId);
        if (!comments.Any())
        {
            return;
        }

        @foreach (var comment in comments)
        {
            <div class="media">
                <h5>@comment.UserFullName</h5>
                @if (this.User.Identity.IsAuthenticated)
                {
                    <button type="button" class="btn btn-secondary pull-right" onclick="showAddCommentForm(@comment.Id)">
                        <i class="fa fa-plus"></i>&nbsp; Answer
                    </button>
                }
                <div class="media-left">
                    <a>
                        <img src="/images/user.jpg" title="Cinema World User" alt="User profile picture" />
                    </a>
                </div>
                <div class="media-body">
                    <p>@Html.Raw(comment.SanitizedContent)</p>
                    <span>Posted by :<a> @comment.UserUserName </a></span>&nbsp;&nbsp;
                    <span><i class="fa fa-calendar" aria-hidden="true"></i> <time datetime="@comment.CreatedOn.ToString("O")"></time></span>
                    @{ DisplayComments(comment.Id); }
                </div>
            </div>
        }
    }
}

<div class="faq">
    <div class="container">
        <div class="agileits-news-top">
            <ol class="breadcrumb">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="News" asp-action="Index">News</a></li>
                <li class="active">Single</li>
            </ol>
        </div>
        <div class="agileinfo-news-top-grids">
            <div class="col-md-8 wthree-top-news-left">
                <div class="wthree-news-left">
                    <div class="wthree-news-left-img">
                        <img src="@Model.News.ImagePath" alt="News Image" />
                        <h4>@Model.News.Title</h4>
                        <div class="s-author">
                            <p>
                                Posted By
                                <i class="fa fa-user" aria-hidden="true"></i> @Model.News.UserUserName
                                &nbsp;&nbsp;
                                <i class="fa fa-calendar" aria-hidden="true"></i> <time datetime="@Model.News.CreatedOn.ToString("O")"></time> &nbsp;&nbsp;
                                <i class="fa fa-comments" aria-hidden="true"></i> Comments (@Model.News.NewsComments.Count())
                            </p>
                        </div>
                        <div class="w3-agile-news-text">
                            @Html.Raw(Model.News.SanitizedDescription)
                        </div>
                    </div>
                </div>
                <div class="all-comments">
                    <div class="all-comments-info">
                        <h3>Comments</h3>
                        <hr />
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <div class="px-4 pt-3">
                                <button type="button" class="btn btn-primary float-right" onclick="showAddCommentForm(0)">
                                    <i class="fa fa-plus"></i>&nbsp; Comment
                                </button>
                            </div>
                        }
                        <script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
                        <script type="text/javascript">
                            tinymce.init({
                                selector: "textarea",
                                plugins: ["image paste table link code media"],
                                setup: function (editor) {
                                    editor.on('change', function (e) {
                                        editor.save();
                                    });
                                }
                            });
                        </script>
                        <div class="agile-info-wthree-box">
                            <form id="AddCommentForm" asp-controller="NewsComments" asp-action="Create" method="post" style="display: none">
                                <input type="hidden" name="NewsId" value="@Model.News.Id" />
                                <input type="hidden" name="ParentId" value="0" />
                                <div class="form-group">
                                    <textarea name="Content" id="Content" placeholder="Message" class="form-control" required=""></textarea>
                                </div>
                                <div>
                                    <input type="submit" value="SEND COMMENT" />
                                </div>
                                <div class="clearfix"> </div>
                            </form>
                        </div>
                    </div>
                    <div class="media-grids">
                        @{ DisplayComments(null); }
                    </div>
                </div>
            </div>
            <div class="col-md-4 wthree-news-right">
                <div class="news-right-bottom">
                    <div class="wthree-news-right-heading">
                        <h3>Top News</h3>
                    </div>
                    <div class="news-right-bottom-bg">
                        <div class="news-grids-bottom">
                            @foreach (var news in Model.TopNews)
                            {
                                <div class="top-news-grid">
                                    <div class="top-news-grid-heading">
                                        <a asp-controller="News" asp-action="Details" asp-route-id="@news.Id">
                                            @news.Title
                                        </a>
                                    </div>
                                    <div class="w3ls-news-t-grid top-t-grid">
                                        <ul>
                                            <li><i class="fa fa-clock-o"></i> @news.CreatedOnBefore h</li>
                                            <li><i class="fa fa-user"></i> @news.UserUserName</li>
                                            <li><i class="fa fa-eye" aria-hidden="true"></i> @news.ViewsCounter</li>
                                        </ul>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="w3l-latest-movies-grids">
        <h4 class="latest-text w3_latest_text">Latest Movies</h4>
        <div class="container">
            <div class="browse-inner">
                @foreach (var latestMovie in Model.LatestMovies)
                {
                    <div class="col-md-2 w3l-movie-gride-agile">
                        <a asp-controller="Movies" asp-action="Details" asp-route-id="@latestMovie.Id" class="hvr-shutter-out-horizontal">
                            <img src="@latestMovie.CoverPath" title="@latestMovie.Name" class="img-responsive" alt="Movie Cover Path" />
                            <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
                        </a>
                        <div class="mid-1">
                            <div class="w3l-movie-text">
                                <h6><a asp-controller="Movies" asp-action="Details" asp-route-id="@latestMovie.Id">@latestMovie.Name</a></h6>
                            </div>
                            <div class="mid-2">
                                <p>@latestMovie.DateOfRelease.Year</p>
                                <div class="block-stars stars_ratings movie_@latestMovie.Id">
                                    <ul class="w3l-ratings">
                                        <li>
                                            <a><i class="fa fa-star-o" aria-hidden="true"></i></a>
                                        </li>
                                        <li>
                                            <a><i class="fa fa-star-o" aria-hidden="true"></i></a>
                                        </li>
                                        <li>
                                            <a><i class="fa fa-star-o" aria-hidden="true"></i></a>
                                        </li>
                                        <li>
                                            <a><i class="fa fa-star-o" aria-hidden="true"></i></a>
                                        </li>
                                        <li>
                                            <a><i class="fa fa-star-o" aria-hidden="true"></i></a>
                                        </li>
                                    </ul>
                                    <div class="starRatingsSum">(@latestMovie.StarRatingsSum)</div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        @if (latestMovie.DateOfRelease.CompareTo(DateTime.UtcNow) > 0)
                        {
                            <div class="ribben">
                                <p>NEW</p>
                            </div>
                        }
                    </div>
                }
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript" src="~/js/rating.js"></script>

    <script>
        function showAddCommentForm(parentId) {
            $("#AddCommentForm input[name='ParentId']").val(parentId);
            $("#AddCommentForm").show();
            $([document.documentElement, document.body]).animate({
                scrollTop: $("#AddCommentForm").offset().top
            }, 1000);
        }
    </script>
}

src/Web/CinemaWorld.Web/Views/News/Index.cshtml
@using CinemaWorld.Models.ViewModels.News
@model NewsIndexViewModel
@{
    ViewData["Title"] = "News";
}

@{
    var prevDisabled = !Model.News.HasPreviousPage ? "disabled" : "";
    var prevPage = !Model.News.HasPreviousPage ? "1" : (Model.News.PageIndex - 1).ToString();
    var nextDisabled = !Model.News.HasNextPage ? "disabled" : "";
    var nextPage = !Model.News.HasNextPage ? "1" : (Model.News.PageIndex + 1).ToString();

    int updatedSinceHourLimit = 12;
}

<div class="faq">
    <div class="container">
        <div class="agileits-news-top">
            <ol class="breadcrumb">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="active">News</li>
            </ol>
        </div>
        <div class="agileinfo-news-top-grids">
            <div class="col-md-8 wthree-top-news-left">
                <div class="wthree-news-left">
                    <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#home1" id="home1-tab" role="tab" data-toggle="tab" aria-controls="home1" aria-expanded="true">Latest News</a></li>
                            <li role="presentation"><a href="#w3bsd" role="tab" id="w3bsd-tab" data-toggle="tab" aria-controls="w3bsd">Movie News</a></li>
                        </ul>
                        <div class="w3ls-news-result">
                            <h4>Total Count : <span>@Model.News.Count()</span></h4>
                        </div>
                        <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="home1" aria-labelledby="home1-tab">
                                @foreach (var news in Model.News)
                                {
                                    <div class="wthree-news-top-left">
                                        <div class="col-md-7 w3-agileits-news-left">
                                            <div class="col-sm-5 wthree-news-img">
                                                <a asp-controller="News" asp-action="Details" asp-route-id="@news.Id">
                                                    <img src="@news.ImagePath" alt="Image" />
                                                </a>
                                            </div>
                                            <div class="col-sm-7 wthree-news-info">
                                                <h5>
                                                    <a asp-controller="News" asp-action="Details" asp-route-id="@news.Id">
                                                        @news.Title
                                                    </a>
                                                </h5>
                                                <p>@news.ShortDescription</p>
                                                <ul>
                                                    <li><i class="fa fa-user" aria-hidden="true"></i> @news.UserUserName</li>
                                                    <li><i class="fa fa-eye" aria-hidden="true"></i> @news.ViewsCounter</li>
                                                </ul>
                                                <ul>
                                                    <li><i class="fa fa-calendar" aria-hidden="true"></i> <time datetime="@news.CreatedOn.ToString("O")"></time></li>
                                                </ul>
                                            </div>
                                            <div class="clearfix"> </div>
                                        </div>
                                        <div class="clearfix"> </div>
                                    </div>
                                }
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="w3bsd" aria-labelledby="w3bsd-tab">
                            @*@for (int i = counter; i < Model.Count(); i++)
                    {
                        <div class="wthree-news-top-left">
                            <div class="col-md-6 w3-agileits-news-left">
                                <div class="col-sm-5 wthree-news-img">
                                    <a asp-controller="News" asp-action="Details" asp-route-id="@Model[i].Id">
                                        <img src="@Model[i].ImagePath" alt="Image" />
                                    </a>
                                </div>
                                <div class="col-sm-7 wthree-news-info">
                                    <h5>
                                        <a asp-controller ="News" asp-action="Details" asp-route-id="@Model[i].Id">
                                            @Model[i].Title
                                        </a>
                                    </h5>
                                    <p>@Model[i].SanitizedShortDescription</p>
                                    <ul>
                                        <li><i class="fa fa-clock-o" aria-hidden="true"></i> @Model[i].CreationDate</li>
                                        <li><i class="fa fa-eye" aria-hidden="true"></i> 2642</li>
                                    </ul>
                                </div>
                                <div class="clearfix"> </div>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    }*@
                        </div>
                    </div>
                </div>
                @if (Model.News.TotalPages != 0)
                {
                    <div class="blog-pagenat-wthree">
                        <ul class="pagination">
                            <li>
                                <a class="frist @prevDisabled" asp-action="Index" asp-route-pageNumber="@prevPage">
                                    Previous
                                </a>
                            </li>
                            @for (int i = 1; i <= Model.News.TotalPages; i++)
                            {
                                var active = i == Model.News.PageIndex ? "active" : string.Empty;
                                <li class="@active">
                                    <a asp-action="Index" asp-route-pageNumber="@i">@i</a>
                                </li>
                            }
                            <li>
                                <a class="last @nextDisabled" asp-action="Index" asp-route-pageNumber="@nextPage">
                                    Next
                                </a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
            <div class="col-md-4 wthree-news-right">
                <!-- news-right-top -->
                <div class="news-right-top">
                    <div class="wthree-news-right-heading">
                        <h3>Updated News</h3>
                    </div>
                    <div class="wthree-news-right-top">
                        <div class="news-grids-bottom">
                            <div id="design" class="date">
                                <div id="cycler">
                                    @foreach (var updatedNewsItem in Model.UpdatedNews)
                                    {
                                        <div class="date-text">
                                            <a asp-controller="News" asp-action="Details" asp-route-id="@updatedNewsItem.Id">
                                                @if (updatedNewsItem.UpdatedSince <= updatedSinceHourLimit 
                                                    && updatedNewsItem.UpdatedSince != null)
                                                {
                                                    <span class="blinking"><img src="images/new.png" alt="Blinking image" /></span>
                                                }
                                                @updatedNewsItem.CreationDate
                                            </a>
                                            <p>@updatedNewsItem.Title</p>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- //news-right-top -->
                <!-- news-right-bottom -->
                <div class="news-right-bottom">
                    <div class="wthree-news-right-heading">
                        <h3>Top News</h3>
                    </div>
                    <div class="news-right-bottom-bg">
                        <div class="news-grids-bottom">
                            @foreach (var news in Model.TopNews)
                            {
                                <div class="top-news-grid">
                                    <div class="top-news-grid-heading">
                                        <a asp-controller="News" asp-action="Details" asp-route-id="@news.Id">
                                            @news.Title
                                        </a>
                                    </div>
                                    <div class="w3ls-news-t-grid top-t-grid">
                                        <ul>
                                            <li><i class="fa fa-clock-o"></i> @news.CreatedOnBefore h</li>
                                            <li><i class="fa fa-user"></i> @news.UserUserName</li>
                                            <li><i class="fa fa-eye" aria-hidden="true"></i> @news.ViewsCounter</li>
                                        </ul>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <!-- //news-right-bottom -->
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        function blinker() {
            $('.blinking').fadeOut(600);
            $('.blinking').fadeIn(600);
        }
        setInterval(blinker, 1000);
    </script>
    <script>
        function cycle($item, $cycler) {
            setTimeout(cycle, 4000, $item.next(), $cycler);
            $item.slideUp(1000, function () {
                $item.appendTo($cycler).show();
            });
        }
        cycle($('#cycler div:first'), $('#cycler'));
    </script>
}