src/Web/CinemaWorld.Web/Controllers/ScheduleController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels;
    using CinemaWorld.Models.ViewModels.Cinemas;
    using CinemaWorld.Models.ViewModels.MovieProjections;
    using CinemaWorld.Models.ViewModels.Movies;
    using CinemaWorld.Models.ViewModels.Schedule;
    using CinemaWorld.Services.Data.Contracts;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class ScheduleController : Controller
    {
        private const int SchedulePageSize = 5;
        private const int LatestMoviesCount = 6;

        private readonly IMovieProjectionsService movieProjectionsService;
        private readonly IMoviesService moviesService;
        private readonly ICinemasService cinemasService;

        public ScheduleController(
            IMovieProjectionsService movieProjectionsService,
            IMoviesService moviesService,
            ICinemasService cinemasService)
        {
            this.movieProjectionsService = movieProjectionsService;
            this.moviesService = moviesService;
            this.cinemasService = cinemasService;
        }

        public async Task<IActionResult> Index(int? pageNumber, string cinemaName)
        {
            this.ViewData["CurrentFilter"] = cinemaName;

            var movieProjections = Enumerable.Empty<MovieProjectionDetailsViewModel>().AsQueryable();

            if (!string.IsNullOrEmpty(cinemaName))
            {
                movieProjections = await Task.Run(
                    () => this.movieProjectionsService
                        .GetAllMovieProjectionsByCinemaAsQueryeable<MovieProjectionDetailsViewModel>(cinemaName));
            }
            else
            {
                movieProjections = await Task.Run(
                    () => this.movieProjectionsService
                        .GetAllMovieProjectionsAsQueryeable<MovieProjectionDetailsViewModel>());
            }

            var movieProjectionsPaginated = await PaginatedList<MovieProjectionDetailsViewModel>
                    .CreateAsync(movieProjections, pageNumber ?? 1, SchedulePageSize);

            var latestMovies = await this.moviesService
                .GetRecentlyAddedMoviesAsync<RecentlyAddedMovieDetailsViewModel>(LatestMoviesCount);

            var cinemas = await this.cinemasService
                .GetAllCinemasAsync<CinemaDetailsViewModel>();

            var viewModel = new ScheduleDetailsViewModel
            {
                MovieProjections = movieProjectionsPaginated,
                LatestMovies = latestMovies,
                Cinemas = cinemas,
            };

            return this.View(viewModel);
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/TicketsController.cs
namespace CinemaWorld.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels.MovieProjections;
    using CinemaWorld.Services.Data.Common;
    using CinemaWorld.Services.Data.Contracts;
    using CinemaWorld.Web.Helpers;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class TicketsController : Controller
    {
        private readonly IMovieProjectionsService movieProjectionsService;
        private readonly ITicketsService ticketsService;
        private readonly ISeatsService seatsService;

        public TicketsController(
            IMovieProjectionsService movieProjectionsService,
            ITicketsService ticketsService,
            ISeatsService seatsService)
        {
            this.movieProjectionsService = movieProjectionsService;
            this.ticketsService = ticketsService;
            this.seatsService = seatsService;
        }

        [Authorize]
        public async Task<IActionResult> Book(int id)
        {
            var movieProjection = await this.movieProjectionsService
                .GetViewModelByIdAsync<MovieProjectionDetailsViewModel>(id);

            var soldSeats = await this.seatsService.GetAllSoldSeatsAsync(movieProjection.Hall.Id);
            var availableSeats = await this.seatsService.GetAllAvailableSeatsAsync(movieProjection.Hall.Id);

            var viewModel = new MovieProjectionViewModel
            {
                MovieProjection = movieProjection,
                SoldSeats = soldSeats,
                AvailableSeats = availableSeats,
            };

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Book(MovieProjectionViewModel movieProjectionViewModel, [FromRoute]int id)
        {
            if (!this.ModelState.IsValid)
            {
                var movieProjection = await this.movieProjectionsService
                    .GetViewModelByIdAsync<MovieProjectionDetailsViewModel>(id);

                var soldSeats = await this.seatsService.GetAllSoldSeatsAsync(movieProjection.Hall.Id);
                var availableSeats = await this.seatsService.GetAllAvailableSeatsAsync(movieProjection.Hall.Id);

                var viewModel = new MovieProjectionViewModel
                {
                    MovieProjection = movieProjection,
                    SoldSeats = soldSeats,
                    AvailableSeats = availableSeats,
                    Ticket = movieProjectionViewModel.Ticket,
                };

                return this.Json(new
                    {
                        Success = false,
                        Model = viewModel,
                        Message = ModelErrorsHelper.GetModelErrors(this.ModelState),
                    });
            }

            try
            {
                var result = await this.ticketsService.BuyAsync(movieProjectionViewModel.Ticket, id);

                return this.Json(new
                    {
                        Success = true,
                        Message = OperationalMessages.SuccessfullyBookedMovieProjection,
                    });
            }
            catch (ArgumentException aex)
            {
                return this.Json(new { Success = false, Message = aex.Message });
            }
        }
    }
}

src/Web/CinemaWorld.Web/Views/Tickets/Book.cshtml
@using CinemaWorld.Models.ViewModels.MovieProjections
@using CinemaWorld.Data.Models.Enumerations
@model MovieProjectionViewModel
@{
    ViewData["Title"] = "Book Ticket";
}

<link href="~/css/book-ticket.css" rel="stylesheet" type="text/css" media="all" asp-append-version="true">

<div class="content">
    <h1>Book Movie Ticket</h1>
    <div class="modal fade" id="bookingModal" role="dialog" aria-labelledby="bookingModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="bookingModalLabel">Information</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="shadow">
                        <div class="lds-dual-ring"></div>
                    </div>
                    <div id="info-message" style="display: none; white-space: pre-line"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a type="button" class="btn btn-primary" asp-controller="Schedule" asp-action="Index">Back to schedule</a>
                </div>
            </div>
        </div>
    </div>
    <div class="main">
        <h2>Multiplex Showing Screen @Model.MovieProjection.Hall.Id</h2>
        <div class="demo">
            <div id="seat-map">
                <div class="front">SCREEN</div>
            </div>
            <div class="booking-details">
                <ul class="book-left">
                    <li>Movie</li>
                    <li>Time</li>
                    <li>Tickets</li>
                    <li>Total</li>
                    <li>Ticket Type</li>
                    <li>Seats</li>
                </ul>
                <form id="bookingFormAjax" asp-controller="Tickets" asp-action="Book" method="post">
                    <ul class="book-right">
                        <li>@Model.MovieProjection.Movie.Name</li>
                        <li>@Model.MovieProjection.Date</li>
                        <li>
                            <span id="counter">0</span>
                            <input asp-for="@Model.Ticket.Quantity" value="0" />
                            <span asp-validation-for="@Model.Ticket.Quantity" class="text-danger"></span>
                        </li>
                        <li>
                            <b>
                                <i>$</i><span id="total">0</span>
                                <input asp-for="@Model.Ticket.Price" value="0" />
                            </b>
                            <span asp-validation-for="@Model.Ticket.Price" class="text-danger"></span>
                        </li>
                    </ul>
                    <select class="selectpicker" data-width="fit" asp-for="@Model.Ticket.TicketType"
                            asp-items="@(Html.GetEnumSelectList<TicketType>())">
                        <option selected="" disabled="">Select Ticket Type</option>
                    </select>
                    <div class="clear"></div>
                    <span asp-validation-for="@Model.Ticket.TicketType" class="text-danger"></span>
                    <input asp-for="@Model.Ticket.MovieProjectionTime" type="hidden" value="@Model.MovieProjection.Date" />
                    <div class="clear"></div>
                    <ul id="selected-seats" class="scrollbar scrollbar1"></ul>
                    <input asp-for="@Model.Ticket.Row" value="0" />
                    <input asp-for="@Model.Ticket.Seat" value="0" />
                    <input id="choosen-seats" name="ChoosenSeats" type="hidden" />
                    <button type="submit" class="checkout-button" data-toggle="modal" data-target="#bookingModal">Book Now</button>
                </form>
                <div id="legend"></div>
            </div>
            <div style="clear:both"></div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript" src="~/js/jquery.seat-charts.js" asp-append-version="true"></script>
    <script type="text/javascript">
        var price = 10; //price

        $(document).ready(function () {
            var $cart = $('#selected-seats'), //Sitting Area
                $ticketCounter = $('#counter'), //Tickets
                $total = $('#total'); //Total money

            let availableSeats = @Html.Raw(Json.Serialize(Model.AvailableSeats));
            var sc = $('#seat-map').seatCharts({
                //Seating chart
                map: availableSeats,
                naming: {
                    top: false,
                    getLabel: function (character, row, column) {
                        return column;
                    }
                },
                legend: { //Definition legend tva e legendata
                    node: $('#legend'),
                    items: [
                        ['a', 'available', 'Available'],
                        ['a', 'unavailable', 'Sold'],
                        ['a', 'selected', 'Selected']
                    ]
                },
                click: function () { //Click event
                    if (this.status() == 'available') { //optional seat
                        $('<li>Row ' + (this.settings.row + 1) + ' / Seat ' + this.settings.label + '</li>')
                            .attr('id', 'cart-item-' + this.settings.id)
                            .data('seatId', this.settings.id)
                            .appendTo($cart);

                        let quantity = sc.find('selected').length + 1;
                        let totalPrice = recalculateTotal(sc) + price;
                        var row = this.settings.row + 1;
                        var seat = this.settings.label;

                        $ticketCounter.text(quantity);
                        $total.text(totalPrice);
                        document.getElementById('Ticket_Quantity').value = quantity;
                        document.getElementById('Ticket_Price').value = totalPrice;
                        document.getElementById('Ticket_Row').value = row;
                        document.getElementById('Ticket_Seat').value = seat;

                        return 'selected';
                    } else if (this.status() == 'selected') { //Checked
                        //Update Number
                        $ticketCounter.text(sc.find('selected').length - 1);
                        //update totalnum
                        $total.text(recalculateTotal(sc) - price);

                        //Delete reservation
                        $('#cart-item-' + this.settings.id).remove();
                        //optional
                        return 'available';
                    } else if (this.status() == 'unavailable') {
                        return 'unavailable';
                    } else {
                        return this.style();
                    }
                }
            });

            //sold seats
            let soldSeats = @Html.Raw(Json.Serialize(Model.SoldSeats));
            sc.get(soldSeats).status('unavailable');
        });

        //sum total money
        function recalculateTotal(sc) {
            var total = 0;
            sc.find('selected').each(function () {
                total += price;
            });

            return total;
        }

        $('#bookingFormAjax').submit(function (event) {
            event.preventDefault();
            var json = { success: false, message: '', action: '' };
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: $('#bookingFormAjax').attr('action'),
                xhrFields: {
                    withCredentials: true
                },
                data: $('#bookingFormAjax').serialize(),
                beforeSend: function () {
                    $('.shadow').show(600);
                },
                success: function (data) {
                    json = data;
                },
                error: function (errorThrown) {
                    json.message = 'Request failed: ' + errorThrown;
                },
                complete: function () {
                    $('.shadow').hide(600);
                    let div = document.getElementById("info-message");

                    if (json.success) {
                        div.style.display = "block";
                        div.innerHTML = json.message;

                        $('#bookingModal').on('hidden.bs.modal', function () {
                            window.location.reload();
                        });
                    }
                    else {
                        div.style.display = "block";
                        div.innerHTML = json.message;
                    }
                }
            });
        });

        // TODO: choose more than one seat in hall
        let selectedSeats = document.getElementById('selected-seats');
        let elements = selectedSeats.getElementsByTagName('li');
    </script>
}