src/Web/CinemaWorld.Web/Areas/Administration/Controllers/ContactsController.cs
namespace CinemaWorld.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using CinemaWorld.Models.InputModels.AdministratorInputModels.Contacts;
    using CinemaWorld.Models.ViewModels.Contacts;
    using CinemaWorld.Services.Data.Contracts;

    using Microsoft.AspNetCore.Mvc;

    public class ContactsController : AdministrationController
    {
        private readonly IContactsService contactsService;

        public ContactsController(IContactsService contactsService)
        {
            this.contactsService = contactsService;
        }

        public async Task<IActionResult> Send()
        {
            var userEmails = await this.contactsService.GetAllUserEmailsAsync<UserEmailViewModel>();

            var model = new SendContactInputModel
            {
                UserEmails = userEmails,
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Send(SendContactInputModel sendContactInputModel)
        {
            if (!this.ModelState.IsValid)
            {
                var userEmails = await this.contactsService.GetAllUserEmailsAsync<UserEmailViewModel>();
                sendContactInputModel.UserEmails = userEmails;

                return this.View(sendContactInputModel);
            }

            await this.contactsService.SendContactToUser(sendContactInputModel);
            return this.RedirectToAction("SuccessfullySend", new { userEmail = sendContactInputModel.Email });
        }

        public IActionResult SuccessfullySend(string userEmail)
        {
            return this.View("SuccessfullySend", userEmail);
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/ContactsController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels.Contacts;
    using CinemaWorld.Services.Data.Contracts;

    using Microsoft.AspNetCore.Mvc;

    public class ContactsController : Controller
    {
        private readonly IContactsService contactsService;

        public ContactsController(IContactsService contactsService)
        {
            this.contactsService = contactsService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormEntryViewModel contactFormViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(contactFormViewModel);
            }

            await this.contactsService.SendContactToAdmin(contactFormViewModel);

            return this.RedirectToAction("ThankYou");
        }

        public IActionResult ThankYou()
        {
            return this.View();
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/MoviesController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels;
    using CinemaWorld.Models.ViewModels.Movies;
    using CinemaWorld.Services.Data.Contracts;
    using CinemaWorld.Web.Helpers;

    using Microsoft.AspNetCore.Mvc;

    public class MoviesController : Controller
    {
        private const int PageSize = 10;

        private readonly IMoviesService moviesService;

        public MoviesController(IMoviesService moviesService)
        {
            this.moviesService = moviesService;
        }

        public async Task<IActionResult> All(string searchString, string currentFilter, string selectedLetter, int? pageNumber)
        {
            this.ViewData["Current"] = nameof(this.All);

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            this.ViewData["CurrentSearchFilter"] = searchString;
            var movies = this.moviesService
                .GetAllMoviesByFilterAsQueryeable<MovieDetailsViewModel>(selectedLetter);

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.Name.ToLower().Contains(searchString.ToLower()));
            }

            var moviesPaginated = await PaginatedList<MovieDetailsViewModel>.CreateAsync(movies, pageNumber ?? 1, PageSize);

            var alphabeticalPagingViewModel = new AlphabeticalPagingViewModel
            {
                SelectedLetter = selectedLetter,
            };

            var viewModel = new MoviesListingViewModel
            {
                Movies = moviesPaginated,
                AlphabeticalPagingViewModel = alphabeticalPagingViewModel,
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await this.moviesService.GetViewModelByIdAsync<MovieDetailsViewModel>(id);
            var topRatingMovies = await this.moviesService.GetAllMoviesAsync<TopRatingMovieDetailsViewModel>();

            string videoId = ExtractVideoHelper.ExtractVideoId(movie.TrailerPath);
            movie.TrailerPath = videoId;

            var viewModel = new DetailsListingViewModel
            {
                MovieDetailsViewModel = movie,
                AllMovies = topRatingMovies,
            };

            return this.View(viewModel);
        }
    }
}

src/Web/CinemaWorld.Web/Areas/Administration/Views/Contacts/Send.cshtml
@model CinemaWorld.Models.InputModels.AdministratorInputModels.Contacts.SendContactInputModel
@{
    this.ViewData["Title"] = "Send email";
    this.ViewData["ActivePage"] = AdminNavPages.Contacts;

    var userEmails = Model.UserEmails.Select(x => new SelectListItem(x.Email + " - " + x.Id, x.Email.ToString()));
}

<div class="row">
    <div class="col-md-6">
        <form asp-area="Administration" asp-controller="Contacts" asp-action="Send" method="post">
            <h4>Send new email</h4>
            <hr />
            <div class="form-group">
                <label asp-for="FullName"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <div class="container">
                    <select asp-for="Email" asp-items="userEmails" class="selectpicker">
                        <option selected="" disabled="">Select User email</option>
                    </select>
                </div>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success">Send email</button>
        </form>
    </div>
</div>

@section Scripts
{
    <script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea",
            plugins: [
                "image paste table link code media"
            ]
        });
    </script>
}

src/Web/CinemaWorld.Web/Areas/Administration/Views/Contacts/SuccessfullySend.cshtml
@model string
@{
    this.ViewData["Title"] = "Success";
}

<div class="alert alert-success col-md-9" role="alert">
    <center><h3 class="alert-heading">You have successfully send message to <strong>@Model</strong>!</h3></center>
    <hr>
    <p class="mb-0">
        <center><a class="btn btn-lg btn-primary" asp-controller="Movies" asp-action="Index" role="button">Back to admin dashboard</a></center>
    </p>
</div>