src/Web/CinemaWorld.Web/Controllers/AboutController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels.About;
    using CinemaWorld.Services.Data.Contracts;
    using Microsoft.AspNetCore.Mvc;

    public class AboutController : Controller
    {
        private readonly IAboutService aboutService;

        public AboutController(IAboutService aboutService)
        {
            this.aboutService = aboutService;
        }

        public async Task<IActionResult> Index()
        {
            var faqs = await this.aboutService.GetAllFaqsAsync<FaqDetailsViewModel>();

            return this.View(faqs);
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/GenresController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels;
    using CinemaWorld.Models.ViewModels.Movies;
    using CinemaWorld.Services.Data.Contracts;

    using Microsoft.AspNetCore.Mvc;

    public class GenresController : Controller
    {
        private const int GenresPerPage = 12;

        private readonly IMoviesService moviesService;

        public GenresController(IMoviesService moviesService)
        {
            this.moviesService = moviesService;
        }

        public async Task<IActionResult> ByName(int? pageNumber, string name)
        {
            var moviesByGenreName = await Task.Run(() => this.moviesService.GetByGenreNameAsQueryable(name));

            if (moviesByGenreName.Count() == 0)
            {
                return this.NotFound();
            }

            this.TempData["GenreName"] = name;
            var moviesByGenreNamePaginated = await PaginatedList<MovieDetailsViewModel>
                    .CreateAsync(moviesByGenreName, pageNumber ?? 1, GenresPerPage);

            return this.View(moviesByGenreNamePaginated);
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/MoviesController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels;
    using CinemaWorld.Models.ViewModels.Movies;
    using CinemaWorld.Services.Data.Contracts;
    using CinemaWorld.Web.Helpers;

    using Microsoft.AspNetCore.Mvc;

    public class MoviesController : Controller
    {
        private const int PageSize = 10;

        private readonly IMoviesService moviesService;

        public MoviesController(IMoviesService moviesService)
        {
            this.moviesService = moviesService;
        }

        public async Task<IActionResult> All(string searchString, string currentFilter, string selectedLetter, int? pageNumber)
        {
            this.ViewData["Current"] = nameof(this.All);

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            this.ViewData["CurrentSearchFilter"] = searchString;
            var movies = this.moviesService
                .GetAllMoviesByFilterAsQueryeable<MovieDetailsViewModel>(selectedLetter);

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.Name.ToLower().Contains(searchString.ToLower()));
            }

            var moviesPaginated = await PaginatedList<MovieDetailsViewModel>.CreateAsync(movies, pageNumber ?? 1, PageSize);

            var alphabeticalPagingViewModel = new AlphabeticalPagingViewModel
            {
                SelectedLetter = selectedLetter,
            };

            var viewModel = new MoviesListingViewModel
            {
                Movies = moviesPaginated,
                AlphabeticalPagingViewModel = alphabeticalPagingViewModel,
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await this.moviesService.GetViewModelByIdAsync<MovieDetailsViewModel>(id);
            var topRatingMovies = await this.moviesService.GetAllMoviesAsync<TopRatingMovieDetailsViewModel>();

            string videoId = ExtractVideoHelper.ExtractVideoId(movie.TrailerPath);
            movie.TrailerPath = videoId;

            var viewModel = new DetailsListingViewModel
            {
                MovieDetailsViewModel = movie,
                AllMovies = topRatingMovies,
            };

            return this.View(viewModel);
        }
    }
}

src/Web/CinemaWorld.Web/Controllers/NewsController.cs
namespace CinemaWorld.Web.Controllers
{
    using System.Threading.Tasks;

    using CinemaWorld.Models.ViewModels;
    using CinemaWorld.Models.ViewModels.Movies;
    using CinemaWorld.Models.ViewModels.News;
    using CinemaWorld.Services.Data.Contracts;

    using Microsoft.AspNetCore.Mvc;

    public class NewsController : Controller
    {
        private const int NewsCount = 6;
        private const int LatestMoviesCount = 6;
        private const int TopMoviesCount = 10;

        private readonly INewsService newsService;
        private readonly IMoviesService moviesService;

        public NewsController(INewsService newsService, IMoviesService moviesService)
        {
            this.newsService = newsService;
            this.moviesService = moviesService;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            var news = await Task.Run(
                () => this.newsService.GetAllNewsAsQueryeable<AllNewsListingViewModel>());

            var newsPaginated = await PaginatedList<AllNewsListingViewModel>
                .CreateAsync(news, pageNumber ?? 1, NewsCount);
            var updatedNews = await this.newsService
                .GetUpdatedNewsAsync<UpdatedNewsDetailsViewModel>();
            var topNews = await this.newsService
                .GetTopNewsAsync<TopNewsViewModel>(TopMoviesCount);

            var viewModel = new NewsIndexViewModel
            {
                News = newsPaginated,
                UpdatedNews = updatedNews,
                TopNews = topNews,
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var news = await this.newsService
                .SetViewsCounter(id);
            var latestMovies = await this.moviesService
                .GetRecentlyAddedMoviesAsync<RecentlyAddedMovieDetailsViewModel>(LatestMoviesCount);
            var topNews = await this.newsService
                .GetTopNewsAsync<TopNewsViewModel>(TopMoviesCount);

            var viewModel = new NewsSingleDetailsViewModel
            {
                News = news,
                LatestMovies = latestMovies,
                TopNews = topNews,
            };

            return this.View(viewModel);
        }
    }
}

src/Web/CinemaWorld.Web/Views/Shared/BookingError.cshtml
@model BookingErrorViewModel
@{
    this.ViewData["Title"] = "Error";
}

<div class="container container_addon">
    <h1 class="text-danger">Error.</h1>
    <h2 class="text-danger">An error occurred while processing your request.</h2>

    @if (this.Model.ShowRequestId)
    {
        <p>
            <strong>Request ID:</strong> <code>@this.Model.RequestId</code>
        </p>
        @if (this.Model.ErrorMessage != null)
        {
            <hr />
            <div class="alert alert-danger">
                @this.Model.ErrorMessage
            </div>
            <div class="grid_3 grid_3 w3">
                <h3>
                    <a asp-controller="Home" asp-action="Index">
                        <span class="label label-primary">Home</span>
                    </a>
                    <a asp-controller="Tickets" asp-action="Book">
                        <span class="label label-primary">Back to booking</span>
                    </a>
                </h3>
            </div>
        }
    }
</div>

src/Web/CinemaWorld.Web/Views/Shared/HttpError.cshtml
@model HttpErrorViewModel
@{
    this.ViewData["Title"] = "Page not found";
}

<div class="container">
    <br />
    <h1>Page not found: @Model.StatusCode</h1>
    <div class="container">
        <h2>We are sorry for that!</h2>
        <img src="~/images/404.png" alt="Not found page">
        <br />
        <div class="container">
            <span>
                We are sorry, the page you requested could not be found. Please go back to the homepage or use the contact form.
                <br />
                Thank your for your understanding!
            </span>
            <div class="grid_3 grid_3 w3">
                <h3>
                    <a asp-controller="Home" asp-action="Index">
                        <span class="label label-primary">Home</span>
                    </a>
                    <a asp-controller="Contacts" asp-action="Index">
                        <span class="label label-primary">Contact</span>
                    </a>
                </h3>
            </div>
        </div>
    </div>
</div>

src/Web/CinemaWorld.Web/Views/Shared/_AjaxLoginPartial.cshtml
@model CinemaWorld.Models.InputModels.Users.AjaxLoginInputModel

<div class="form">
    <h3>Login to your account</h3>
    <form id="formLoginAjax" asp-area="" asp-controller="Users" asp-action="AjaxLogin" method="post">
        <div class="shadow">
            <div class="lds-dual-ring"></div>
        </div>
        <span id="login-error" class="text-danger" style="display: none; white-space: pre-line"></span>
        <input asp-for="Username" placeholder="Username">
        <input asp-for="Password" placeholder="Password">
        <input type="submit" value="Login">
        <hr />
    </form>
    <form asp-area="" asp-controller="Users" asp-action="FacebookLogin" method="post">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Login with Facebook</button>
    </form>
</div>

<script>
    $('#formLoginAjax').submit(function (event) {
        event.preventDefault();
        var json = { success: false, message: '', action: '' };
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url: $('#formLoginAjax').attr('action'),
            xhrFields: {
                withCredentials: true
            },
            data: $('#formLoginAjax').serialize(),
            beforeSend: function () {
                $('.shadow').show(900);
            },
            success: function (data) {
                json = data;
            },
            error: function (errorThrown) {
                json.message = 'Request failed: ' + errorThrown;
            },
            complete: function () {
                $('.shadow').hide(900);
                if (json.success) {
                    $('#myModal').modal('hide');
                    window.location = json.action;
                }
                else {
                    let span = document.getElementById("login-error");
                    span.style.display = "block";
                    span.style.marginBottom = "2.5vh"; // 2,5% from virtual screen
                    span.innerHTML = json.message;
                }
            }
        });
    });
</script> 

src/Web/CinemaWorld.Web/Views/Shared/_AjaxPartial.cshtml
@using CinemaWorld.Models.InputModels.Users
@using CinemaWorld.Data.Models.Enumerations
@{
    var genders = new[] { nameof(Gender.Male), nameof(Gender.Female) };
}

<div class="w3l_sign_in_register">
    <ul>
        <li><i class="fa fa-phone" aria-hidden="true"></i> (+000) 123 345 653</li>
        <li><a data-toggle="modal" data-target="#myModal">Login</a></li>
    </ul>
</div>

<div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                Sign In & Sign Up
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <section>
                <div class="modal-body">
                    <div class="w3_login_module">
                        <div class="module form-module">
                            <div class="toggle">
                                <i class="fa fa-times fa-pencil"></i>
                                <div class="tooltip">Register</div>
                            </div>
                            <partial name="_AjaxLoginPartial" model="new AjaxLoginInputModel()" />
                            <partial name="_AjaxRegisterPartial" model="new AjaxRegisterInputModel { Genders = genders }" />
                            <div class="cta"><a id="forgot-password" href="/Identity/Account/ForgotPassword">Forgot your password?</a></div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

src/Web/CinemaWorld.Web/Views/Shared/_AjaxRegisterPartial.cshtml
@model CinemaWorld.Models.InputModels.Users.AjaxRegisterInputModel

<div class="form">
    <h3>Create an account</h3>
    <form id="formRegisterAjax" asp-area="" asp-controller="Users" asp-action="AjaxRegister" method="post">
        <div class="shadow">
            <div class="lds-dual-ring"></div>
        </div>
        <span id="register-error" class="text-danger" style="display: none; white-space: pre-line"></span>
        <input asp-for="Username" placeholder="Username">
        <input asp-for="FullName" placeholder="Full Name">
        <input asp-for="Password" placeholder="Password">
        <input asp-for="ConfirmPassword" placeholder="Confirm password">
        <input asp-for="Email" placeholder="Email Address">
        <div class="form-group form-check-inline">
            @foreach (var gender in Model.Genders)
            {
                <input type="radio" asp-for="SelectedGender" value="@gender" class="form-check-input" />@gender
            }
        </div>
        <hr />
        <input type="submit" value="Register">
    </form>
</div>

<script>
    $('#formRegisterAjax').submit(function (event) {
        event.preventDefault();
        var res = { success: false, message: '', action: '' };
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url: $('#formRegisterAjax').attr('action'),
            xhrFields: {
                withCredentials: true
            },
            data: $('#formRegisterAjax').serialize(),
            beforeSend: function () {
                $('.shadow').show(900);
            },
            success: function (data) {
                res = data;
            },
            error: function (errorThrown) {
                res.message = 'Request failed: ' + errorThrown;
            },
            complete: function () {
                $('.shadow').hide(900);
                if (res.success) {
                    $('#myModal').modal('hide');
                    window.location = res.action;
                }
                else {
                    let span = document.getElementById("register-error");
                    span.style.display = "block";
                    span.style.marginBottom = "2.5vh"; // 2,5% from virtual screen
                    span.innerHTML = res.message;
                }
            }
        });
    });
</script>

src/Web/CinemaWorld.Web/Views/Shared/_FooterPartial.cshtml
<div class="footer">
    <div class="container">
        <div class="w3ls_footer_grid">
            <div class="col-md-6 w3ls_footer_grid_left">
                <div class="w3ls_footer_grid_left1">
                    <h2>Subscribe to us</h2>
                    <div class="w3ls_footer_grid_left1_pos">
                        <div class="sendgrid-subscription-widget widget-2305" data-emailerror="Please enter a valid email address" data-nameerror="Please enter your name" data-checkboxerror="Please tick the box to accept our conditions">
                            <form class="sg-widget" data-token="0e31599c21b049751d32146e7845aec8" onsubmit="return false;">
                                <div class="sg-response"></div>
                                <input class="sg_email" type="email" name="sg_email" placeholder="your_email@example.com" required="required">
                                <input type="submit" class="sg-submit-btn" id="widget-2305" value="Subscribe">
                                <div class="sg-consent-text">
                                    <label>
                                        <input type="checkbox" class="sg_consent_checkbox" name="sg_consent_checkbox"> I understand and consent to the following
                                    </label>
                                    <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Notice</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 w3ls_footer_grid_right">
                <a asp-area="" asp-controller="Home" asp-action="Index"><h2>Cinema<span>World</span></h2></a>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="col-md-5 w3ls_footer_grid1_left">
            <p>&copy; @DateTime.UtcNow.Year Cinema World. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
            <p><a href="https://github.com/stanislavstoyanov99/CinemaWorld">Open source project</a></p>
        </div>
        <div class="col-md-7 w3ls_footer_grid1_right">
            <ul>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="News" asp-action="Index">News</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Schedule" asp-action="Index">Schedule</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="About" asp-action="Index">FAQ</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Genres" asp-action="ByName" asp-route-name="Action">Action</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Genres" asp-action="ByName" asp-route-name="Adventure">Adventure</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Genres" asp-action="ByName" asp-route-name="Comedy">Comedy</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Genres" asp-action="ByName" asp-route-name="Drama">Drama</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Contacts" asp-action="Index">Contact Us</a>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>

<script type="text/javascript" defer src="//app.sgwidget.com/js/sg-widget-v2.js"></script>

src/Web/CinemaWorld.Web/Views/Shared/_NavbarPartial.cshtml
@inject CinemaWorld.Services.Data.Contracts.IGenresService GenresService
@using CinemaWorld.Models.ViewModels.Genres

@{
    var genres = await GenresService.GetAllGenresAsync<NavbarGenreViewModel>();
}

<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header navbar-left">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
            <nav>
                <ul class="nav navbar-nav">
                    <li active-when="/Home/Index"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li active-when="/Movies/All"><a asp-area="" asp-controller="Movies" asp-action="All">Movies</a></li>
                    <li active-when="/Genres/ByName" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Genres <b class="caret"></b></a>
                        <ul class="dropdown-menu multi-column columns-3">
                            <li>
                                <cache expires-after="@TimeSpan.FromDays(30)" vary-by="@genres.Count().ToString()">
                                    @foreach (var genre in genres)
                                    {
                                        <div class="col-sm-4">
                                            <ul class="multi-column-dropdown">
                                                <li>
                                                    <a asp-area="" asp-controller="Genres" asp-action="ByName" asp-route-name="@genre.Name">@genre.Name</a>
                                                </li>
                                            </ul>
                                        </div>
                                    }
                                </cache>
                                <div class="clearfix"></div>
                            </li>
                        </ul>
                    </li>
                    <li active-when="/News/Index"><a asp-area="" asp-controller="News" asp-action="Index">News</a></li>
                    <li active-when="/Schedule/Index"><a asp-area="" asp-controller="Schedule" asp-action="Index">Schedule</a></li>
                </ul>
            </nav>
        </div>
    </nav>
</div>